t1=(3,4,2,9,5,1,6)
t2=('dell', 'hp', 'lenovo', 'asus')
len(t1)
print(len(t1))
max(t1)
print(max(t1))
min(t1)
print(min(t1))
sum(t1)
print(sum(t1))
sorted(t1)
print(sorted(t1))
sorted(t2)
print(sorted(t2))
t2.count('dell')
print(t2.count('dell'))
t2.index('lenovo')
print(t2.index('lenovo'))
